### PR TITLE
Add rebar3_format plugin

### PR DESCRIPTION
**Pull request by lukebakken**
Using `osiris` as a model:

https://github.com/rabbitmq/osiris/pull/11

Supersedes #28

### CODE REVIEW

**Comment by lukebakken** [comment]
@dumbbell I did not run this on all files yet. Let me know if / when it would be a good time to do that.

**Comment by dumbbell** [comment]
I took some time this morning to look at the formatting of ` rebar3_format`'s default formatter, as well as the two other formatters it can use, streamroller and erlfmt. Unfortunately, the results are horrible with all of them :-/

The closest to something acceptable would be erlfmt, but there is still a lot of rewrite necessary to make the code readable again (at least to me).

**Comment by lukebakken** [comment]
Thanks @dumbbell. I personally would like something that auto-formats code. Right now I just use what `vim` provides which may or may not be what we like.

I think `rebar3_format` allows quite a bit of customization. If you have time, would you mind putting together one example of how you like code to be formatted vs how `rebar3_format` changes it? Then I could see if settings could be adjusted.

It would be nice to have "the one true way" for auto-formatting code in all our projects.

**Comment by dumbbell** [comment]
Sorry @lukebakken, I didn't come back to you...

I like most of the layout decisions of erlfmt. My main concern is its formatting of function headers. Here are some examples from `khepri_machine`:
```erlang
remove_node_child_nodes(
    #node{child_nodes = Children} = Node
) when Children =:= #{} ->
    Node;
remove_node_child_nodes(
    #node{stat = #{child_list_version := CVersion} = Stat} = Node
) ->
    Stat1 = Stat#{child_list_version => CVersion + 1},
    Node#node{stat = Stat1, child_nodes = #{}}.
```

```erlang
walk_down_the_tree1(
    CurrentNode,
    [?ROOT_NODE | PathPattern],
    WorkOnWhat,
    ReversedPath,
    ReversedParentTree,
    Extra,
    Fun,
    FunAcc
) ->
    ?assertEqual([], ReversedPath),
    ?assertEqual([], ReversedParentTree),
    walk_down_the_tree1(
        CurrentNode,
        PathPattern,
        WorkOnWhat,
        ReversedPath,
        ReversedParentTree,
        Extra,
        Fun,
        FunAcc
    );
```

```erlang
handle_keep_while_aftermath(
    Root,
    #{keep_while_aftermath := KeepWhileAftermath} = Extra,
    FunAcc
) when
    KeepWhileAftermath =:= #{}
->
    {ok, Root, Extra, FunAcc};
```

I find them really hard to read ot the point I don't see where the function header stops and the function body starts.

Let me try the other formatters again and report in another comment.

**Comment by dumbbell** [comment]
Here is the configuration I played with:

* erlfmt:
    ```erlang
    {erlfmt, [
        write,
        {print_width, 80},
        {files, [
            "rebar.config",
            "rebar.config.script",
            "{src,include,test}/*.{hrl,erl}"
        ]}
    ]}.
    ```
* rebar3_format:
    ```erlang
    {format, [
        {files, [
            "rebar.config",
            "rebar.config.script",
            "{src,include,test}/*.{hrl,erl}"
        ]},
        {formatter, default_formatter},
        {options, #{
            paper => 79,
            ribbon => 69,
            break_indent => 4,
            sub_indent => 2,
            truncate_strings => true,
            inline_attributes => {when_under, 1},
            inline_items => {when_under, 4}
        }}
    ]}.
    ```

**Comment by lukebakken** [comment]
You know it's 2022, it's OK to have lines wider than 80 characters 😉

**Comment by lukebakken** [comment]
It doesn't seem like auto-formatting is appropriate then. Cheers!

**Comment by dumbbell** [comment]
The limit of 80 columns is not the problem with the formatting plugins I tried. They work just fine with 80 or 100 columns. My concern is about a couple other decisions they make and I can't figure out how to configure them to tune those decisions.

**Comment by lukebakken** [comment]
> My concern is about a couple other decisions they make and I can't figure out how to configure them to tune those decisions.

Yep! Exactly. It's no big deal!

**Pull request closed without merging**
