### PR TITLE
Support Erlang/OTP 25

### PR DESCRIPTION
**Pull request by dumbbell**
This includes at least the support of the new `bs_create_bin` instruction.

### CODE REVIEW

**Comment by dumbbell** [comment]
I think the `bs_create_bin` instruction arguments are only partially decoded. In particular, it could have strings among its variable list of arguments. Strings are supposed to have a `{string, Binary}` element, but we only get a `{u, Integer}` from `beam_disasm`. Indeed, the `decode_arg()` function in `beam_disasm` never produces strings.

Perhaps the code is incomplete. I will compare that to `beam_load.c` to understand what's missing. This time, it will probably be difficult to implement a fix in `khepri_fun` because we lack information. We can submit a patch upstream of course, but we might need to consider a fork of that module if the Erlang release calendar doesn't fit our need.

**Comment by dumbbell** [comment]
> Strings are supposed to have a `{string, Binary}` element, but we only get a `{u, Integer}` from `beam_disasm`.

In fact, the instruction's string really has an integer in the beam file in place of a binary. That's because it's an index into a table elsewhere in the beam file. Exactly like the `line` instructions pointing to entries in the "Line" chunk.

**Comment by dumbbell** [comment]
We can't test automatically against Erlang 25 in GitHub Actions for now. There is no prebuilt versions available on repo.hex.pm and the `setup_beam` action doesn't know about Erlang 25 yet.

This explains the drop in code coverage: the new `bs_create_bin` instruction is introduced in Erlang 25 only.

**Comment by michaelklishin** [comment]
@dumbbell should we use a list of tasks to keep track of what else we might want to support?
This PR works great on Erlang 25 (the tip).

**Comment by the-mikedavis** [comment]
The new [`call_fun2/3`](https://github.com/erlang/otp/blob/41f5ee8cf217d10bd3a736a948d5335f591a2b85/lib/compiler/src/genop.tab#L664) instruction might fall under this (#19). I'll see if I can make a test case that can produce it.

**Comment by dumbbell** [comment]
> @dumbbell should we use a list of tasks to keep track of what else we might want to support?

Thank you for testing!

In fact, I was thinking to just merge this current patch, if it works for anyone, not just me. I would feel better if I could run tests against Erlang 25 in CI as well but that won't happen soon, I guess.

After that, Erlang 25 will be officially supported and we will probably need more patches along the road to keep it working. That's the same for previous versions of Erlang: we continue to discover cases where a Beam instruction is unsupported by Khepri, with both Erlang 23 and Erlang 24.

**Comment by michaelklishin** [comment]
@dumbbell SGTM

**Comment by dumbbell** [comment]
> I would feel better if I could run tests against Erlang 25 in CI as well but that won't happen soon, I guess.

In fact, I misread the code of `erlef/setup-beam` and the bot that deploys builds of Erlang to repo.hex.pm. There are snapshots of `main` and `maint` compiled every day and every release tags are published, including release candidates.

I just enabled Erlang 25 using 25.0-rc3 in CI (see #88).

**Pull request merged**
